import prisma from './db';
import { syncCustomerToMikrotik } from './mikrotik';
import { generateBillingPDF } from './pdf-report';

/**
 * Automatically checks and generates invoices for all ACTIVE customers
 * whose due date and due time for the current or past months have passed, but do not
 * have an invoice generated yet.
 */
export async function autoGenerateDueInvoices() {
  try {
    const customers = await prisma.customer.findMany({
      where: {
        status: 'ACTIVE'
      },
      include: {
        package: true
      }
    });

    const currentDate = new Date();
    let generatedCount = 0;

    for (const customer of customers) {
      if (!customer.package) continue;

      const joinDateObj = new Date(customer.joinDate);
      
      // Start iterating from the month customer joined
      let iterDate = new Date(joinDateObj.getFullYear(), joinDateObj.getMonth(), 1);
      
      // Stop checking at the current month
      const endDate = new Date(currentDate.getFullYear(), currentDate.getMonth(), 1);

      while (iterDate <= endDate) {
        const year = iterDate.getFullYear();
        const monthNum = iterDate.getMonth();
        const monthStr = `${year}-${String(monthNum + 1).padStart(2, '0')}`; // "YYYY-MM"

        // Determine actual due date and time for this specific month
        const [dueHour, dueMinute] = (customer.dueTime || '10:00').split(':').map(Number);
        
        // Handle month end clamping (e.g. if due date is 31 but month only has 30 days)
        const lastDayOfMonth = new Date(year, monthNum + 1, 0).getDate();
        const clampedDueDate = Math.min(customer.dueDate, lastDayOfMonth);
        
        const dueDateTime = new Date(year, monthNum, clampedDueDate, dueHour ?? 10, dueMinute ?? 0, 0, 0);

        // Skip generating invoice for the join month if they joined after the due date of that month
        if (year === joinDateObj.getFullYear() && monthNum === joinDateObj.getMonth()) {
          if (joinDateObj > dueDateTime) {
            // Move to next month
            iterDate.setMonth(iterDate.getMonth() + 1);
            continue;
          }
        }

        // Generate the invoice on or after the anniversary due date and time
        if (currentDate >= dueDateTime) {
          // Check if invoice already exists for this customer and month
          const existing = await prisma.invoice.findUnique({
            where: {
              customerId_month: {
                customerId: customer.id,
                month: monthStr
              }
            }
          });

          if (!existing) {
            const baseAmount = customer.package.price;
            const carriedOver = customer.carriedOverDebt || 0;
            const finalAmount = baseAmount + carriedOver;

            await prisma.invoice.create({
              data: {
                customerId: customer.id,
                month: monthStr,
                amount: finalAmount,
                discount: customer.discount || 0,
                status: 'UNPAID',
              }
            });

            if (carriedOver > 0) {
              await prisma.customer.update({
                where: { id: customer.id },
                data: { carriedOverDebt: 0 }
              });
              console.log(`[Auto-Billing] Carried over debt of ${carriedOver} was applied to new invoice for ${customer.name}`);
            }

            generatedCount++;
            console.log(`[Auto-Billing] Generated unpaid invoice for ${customer.name} (${monthStr}) due at ${dueDateTime.toISOString()}`);
          }
        }

        // Move to the next month
        iterDate.setMonth(iterDate.getMonth() + 1);
      }
    }



    // Automatically trigger daily Telegram and WhatsApp report if there are overdue invoices
    // Runs in the background without blocking the main response
    sendTelegramOverdueReport(false).catch(err => {
      console.error('[Auto-Billing] Failed to trigger auto Telegram report:', err);
    });
    
    sendWhatsAppOverdueReport(false).catch(err => {
      console.error('[Auto-Billing] Failed to trigger auto WhatsApp report:', err);
    });

    return generatedCount;
  } catch (error) {
    console.error('[Auto-Billing] Error in auto-generating invoices:', error);
    return 0;
  }
}

/**
 * Sends a list of overdue customers (past their due date and status UNPAID)
 * to the Admin's configured Telegram Chat ID.
 * @param {boolean} force - If true, bypasses the daily check and sends immediately.
 */
export async function sendTelegramOverdueReport(force = false) {
  try {
    const settings = await prisma.systemSettings.findUnique({
      where: { id: 'default' }
    });

    if (!settings || !settings.telegramBotToken || !settings.telegramChatId) {
      console.log('[Telegram-Billing] Telegram settings not configured. Skipping.');
      return false;
    }

    const currentDate = new Date();
    const todayStr = currentDate.toISOString().substring(0, 10); // "YYYY-MM-DD"

    if (!force && settings.lastSentDate === todayStr) {
      console.log(`[Telegram-Billing] Report already sent today (${todayStr}). Skipping.`);
      return false;
    }

    // Get all unpaid invoices
    const unpaidInvoices = await prisma.invoice.findMany({
      where: {
        status: 'UNPAID',
      },
      include: {
        customer: {
          include: {
            package: true
          }
        }
      }
    });

    const todayStart = new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate(), 0, 0, 0, 0);
    const todayEnd = new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate(), 23, 59, 59, 999);

    const isSameDay = (d1, d2) => {
      return d1.getFullYear() === d2.getFullYear() &&
             d1.getMonth() === d2.getMonth() &&
             d1.getDate() === d2.getDate();
    };

    const dueTodayCustomers = {};
    const overdueCustomers = {};

    for (const inv of unpaidInvoices) {
      if (!inv.customer) continue;

      const [year, monthVal] = inv.month.split('-').map(Number);
      const [dueHour, dueMinute] = (inv.customer.dueTime || '10:00').split(':').map(Number);
      const lastDayOfMonth = new Date(year, monthVal, 0).getDate();
      const clampedDueDate = Math.min(inv.customer.dueDate, lastDayOfMonth);
      const dueDateTime = new Date(year, monthVal - 1, clampedDueDate, dueHour, dueMinute, 0, 0);

      // Skip future bills that aren't due today or in the past
      if (dueDateTime > todayEnd) {
        continue;
      }

      const invNominal = inv.amount - (inv.discount || 0);

      if (isSameDay(currentDate, dueDateTime)) {
        if (!dueTodayCustomers[inv.customerId]) {
          dueTodayCustomers[inv.customerId] = {
            customer: inv.customer,
            invoices: [],
            totalAmount: 0
          };
        }
        dueTodayCustomers[inv.customerId].invoices.push(inv);
        dueTodayCustomers[inv.customerId].totalAmount += invNominal;
      } else if (dueDateTime < todayStart) {
        if (!overdueCustomers[inv.customerId]) {
          overdueCustomers[inv.customerId] = {
            customer: inv.customer,
            invoices: [],
            totalAmount: 0
          };
        }
        overdueCustomers[inv.customerId].invoices.push(inv);
        overdueCustomers[inv.customerId].totalAmount += invNominal;
      }
    }

    const todayKeys = Object.keys(dueTodayCustomers);
    const overdueKeys = Object.keys(overdueCustomers);

    if (todayKeys.length === 0 && overdueKeys.length === 0) {
      console.log('[Telegram-Billing] No invoices due today or overdue found.');
      return false;
    }

     // Format values
     const formatRupiah = (val) => {
       return new Intl.NumberFormat('id-ID', {
         style: 'currency',
         currency: 'IDR',
         maximumFractionDigits: 0
       }).format(val);
     };
 
     const getReadableMonth = (monthStr) => {
       const [year, month] = monthStr.split('-');
       const monthNames = [
         "Januari", "Februari", "Maret", "April", "Mei", "Juni",
         "Juli", "Agustus", "September", "Oktober", "November", "Desember"
       ];
       return `${monthNames[parseInt(month) - 1]} ${year}`;
     };

     // Calculate counts & sums first
     let totalTodayAmount = 0;
     let todayCount = 0;
     for (const customerId of todayKeys) {
       totalTodayAmount += dueTodayCustomers[customerId].totalAmount;
       todayCount++;
     }

     let totalOverdueAmount = 0;
     let overdueCount = 0;
     for (const customerId of overdueKeys) {
       totalOverdueAmount += overdueCustomers[customerId].totalAmount;
       overdueCount++;
     }

      // ── Generate Professional PDF Report ──
      const dateStrForPDF = currentDate.toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' });
      const appUrl = 'https://billing.access.daragroup.cloud';

      const pdfBuffer = await generateBillingPDF({
        dateStr: dateStrForPDF,
        dueTodayCustomers,
        overdueCustomers,
        todayKeys,
        overdueKeys,
        totalTodayAmount,
        totalOverdueAmount,
        todayCount,
        overdueCount,
        formatRupiah,
        getReadableMonth,
      });
      console.log(`[Telegram-Billing] PDF generated successfully (${pdfBuffer.length} bytes)`);

      // Build the summary message caption
      let caption = `📊 *LAPORAN PENAGIHAN DARANET*\n`;
      caption += `📅 *Tanggal:* ${dateStrForPDF}\n`;
      caption += `━━━━━━━━━━━━━━━━━━━━━\n\n`;

      caption += `📅 *Jatuh Tempo Hari Ini:* ${formatRupiah(totalTodayAmount)} (${todayCount} pelanggan)\n`;
      caption += `🚨 *Total Tunggakan:* ${formatRupiah(totalOverdueAmount)} (${overdueCount} pelanggan)\n`;
      caption += `📈 *Grand Total Outstanding:* *${formatRupiah(totalTodayAmount + totalOverdueAmount)}*\n\n`;

      caption += `━━━━━━━━━━━━━━━━━━━━━\n`;
      caption += `_File PDF terlampir berisi rincian lengkap pelanggan, wilayah/rute, nominal, dan status tagihan._`;

      // ── Send PDF to Telegram ──
      const telegramUrl = `https://api.telegram.org/bot${settings.telegramBotToken}/sendDocument`;
      const pdfFormData = new FormData();
      pdfFormData.append('chat_id', settings.telegramChatId);
      const pdfBlob = new Blob([pdfBuffer], { type: 'application/pdf' });
      pdfFormData.append('document', pdfBlob, `laporan_penagihan_${todayStr}.pdf`);
      pdfFormData.append('caption', caption);
      pdfFormData.append('parse_mode', 'Markdown');

      const response = await fetch(telegramUrl, {
        method: 'POST',
        body: pdfFormData
      });

      if (!response.ok) {
        const errText = await response.text();
        throw new Error(`Telegram API returned error: ${errText}`);
      }

    // Update lastSentDate
    await prisma.systemSettings.update({
      where: { id: 'default' },
      data: { lastSentDate: todayStr }
    });

    console.log(`[Telegram-Billing] Overdue/Due-today report successfully sent to Telegram chat ${settings.telegramChatId}`);
    return true;
  } catch (error) {
    console.error('[Telegram-Billing] Failed to send Telegram overdue report:', error);
    return false;
  }
}

/**
 * Sends individual WhatsApp reminders to overdue customers via Fonnte API,
 * and an optional summary to the admin.
 * @param {boolean} force - If true, bypasses the daily check and sends immediately.
 */
export async function sendWhatsAppOverdueReport(force = false) {
  try {
    const settings = await prisma.systemSettings.findUnique({
      where: { id: 'default' }
    });

    if (!settings || !settings.fonnteBotToken) {
      console.log('[WA-Billing] Fonnte token not configured. Skipping.');
      return false;
    }

    const currentDate = new Date();
    const todayStr = currentDate.toISOString().substring(0, 10); // "YYYY-MM-DD"

    if (!force && settings.lastSentWaDate === todayStr) {
      console.log(`[WA-Billing] WhatsApp report already sent today (${todayStr}). Skipping.`);
      return false;
    }

    // Get all unpaid invoices
    const unpaidInvoices = await prisma.invoice.findMany({
      where: {
        status: 'UNPAID',
      },
      include: {
        customer: {
          include: {
            package: true
          }
        }
      }
    });

    const overdueList = [];

    for (const inv of unpaidInvoices) {
      if (!inv.customer) continue;

      const [year, monthVal] = inv.month.split('-').map(Number);
      const [dueHour, dueMinute] = (inv.customer.dueTime || '10:00').split(':').map(Number);
      const lastDayOfMonth = new Date(year, monthVal, 0).getDate();
      const clampedDueDate = Math.min(inv.customer.dueDate, lastDayOfMonth);
      const dueDateTime = new Date(year, monthVal - 1, clampedDueDate, dueHour, dueMinute, 0, 0);

      if (currentDate >= dueDateTime) {
        overdueList.push(inv);
      }
    }

    if (overdueList.length === 0) {
      console.log('[WA-Billing] No overdue customers found.');
      return false;
    }

    const formatRupiah = (val) => {
      return new Intl.NumberFormat('id-ID', {
        style: 'currency',
        currency: 'IDR',
        maximumFractionDigits: 0
      }).format(val);
    };

    const getReadableMonth = (monthStr) => {
      const [year, month] = monthStr.split('-');
      const monthNames = [
        "Januari", "Februari", "Maret", "April", "Mei", "Juni",
        "Juli", "Agustus", "September", "Oktober", "November", "Desember"
      ];
      return `${monthNames[parseInt(month) - 1]} ${year}`;
    };

    const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
    
    // Prepare Fonnte request
    const fonnteUrl = 'https://api.fonnte.com/send';
    let successCount = 0;

    for (const inv of overdueList) {
      const formattedPhone = inv.customer.phone.replace(/[^0-9]/g, '');
      let cleanPhone = formattedPhone;
      if (formattedPhone.startsWith('0')) {
        cleanPhone = '62' + formattedPhone.substring(1);
      }

      const invNominal = inv.amount - (inv.discount || 0);
      const appUrl = 'https://billing.access.daragroup.cloud';
      let message = `Halo Bpk/Ibu *${inv.customer.name}*,\n\n`;
      message += `Kami dari *DaraNet ISP* mengingatkan bahwa tagihan internet bulan *${getReadableMonth(inv.month)}* telah *MELEWATI JATUH TEMPO*.\n\n`;
      message += `Detail Tagihan:\n`;
      message += `- Paket: ${inv.customer.package?.name || '-'}\n`;
      message += `- Total Tagihan: *${formatRupiah(invNominal)}*\n\n`;
      message += `Lihat invoice & bayar online (QRIS/VA) di sini:\n${appUrl}/invoice/${inv.id}\n\n`;
      message += `Mohon segera melakukan pembayaran.\n\n`;
      message += `Terima kasih.\n_DaraNet ISP_`;

      try {
        const res = await fetch(fonnteUrl, {
          method: 'POST',
          headers: {
            'Authorization': settings.fonnteBotToken,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            target: cleanPhone,
            message: message,
            delay: "2" // 2 seconds delay
          })
        });

        if (res.ok) {
          successCount++;
        }
        
        // Wait to avoid rate limits
        await delay(2000);
      } catch (err) {
        console.error(`[WA-Billing] Failed to send to ${cleanPhone}:`, err);
      }
    }

    // Send summary to Admin if configured
    if (settings.fonnteTargetPhone) {
      let adminPhone = settings.fonnteTargetPhone.replace(/[^0-9]/g, '');
      if (adminPhone.startsWith('0')) {
        adminPhone = '62' + adminPhone.substring(1);
      }
      
      const adminMessage = `*🤖 Bot DaraNet*\n\nBerhasil mengirim peringatan tagihan (Overdue) ke ${successCount} dari ${overdueList.length} pelanggan.`;
      
      fetch(fonnteUrl, {
        method: 'POST',
        headers: {
          'Authorization': settings.fonnteBotToken,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          target: adminPhone,
          message: adminMessage
        })
      }).catch(e => console.error('[WA-Billing] Admin summary failed:', e));
    }

    // Update lastSentWaDate
    await prisma.systemSettings.update({
      where: { id: 'default' },
      data: { lastSentWaDate: todayStr }
    });

    console.log(`[WA-Billing] WhatsApp report sent to ${successCount} customers.`);
    return true;
  } catch (error) {
    console.error('[WA-Billing] Failed to send WhatsApp overdue report:', error);
    return false;
  }
}
