import prisma from './db';

/**
 * Automatically checks and generates invoices for all ACTIVE or GRACE_PERIOD customers
 * whose due date and due time for the current or past months have passed, but do not
 * have an invoice generated yet.
 */
export async function autoGenerateDueInvoices() {
  try {
    const customers = await prisma.customer.findMany({
      where: {
        status: { in: ['ACTIVE', 'GRACE_PERIOD'] }
      },
      include: {
        package: true
      }
    });

    const currentDate = new Date();
    let generatedCount = 0;

    for (const customer of customers) {
      if (!customer.package) continue;

      const joinDateObj = new Date(customer.joinDate);
      
      // Start iterating from the month customer joined
      let iterDate = new Date(joinDateObj.getFullYear(), joinDateObj.getMonth(), 1);
      
      // Stop checking at the current month
      const endDate = new Date(currentDate.getFullYear(), currentDate.getMonth(), 1);

      while (iterDate <= endDate) {
        const year = iterDate.getFullYear();
        const monthNum = iterDate.getMonth();
        const monthStr = `${year}-${String(monthNum + 1).padStart(2, '0')}`; // "YYYY-MM"

        // Determine actual due date and time for this specific month
        const [dueHour, dueMinute] = (customer.dueTime || '10:00').split(':').map(Number);
        
        // Handle month end clamping (e.g. if due date is 31 but month only has 30 days)
        const lastDayOfMonth = new Date(year, monthNum + 1, 0).getDate();
        const clampedDueDate = Math.min(customer.dueDate, lastDayOfMonth);
        
        const dueDateTime = new Date(year, monthNum, clampedDueDate, dueHour ?? 10, dueMinute ?? 0, 0, 0);

        // If the current date & time has passed the due date & time
        if (currentDate >= dueDateTime) {
          // Check if invoice already exists for this customer and month
          const existing = await prisma.invoice.findUnique({
            where: {
              customerId_month: {
                customerId: customer.id,
                month: monthStr
              }
            }
          });

          if (!existing) {
            await prisma.invoice.create({
              data: {
                customerId: customer.id,
                month: monthStr,
                amount: customer.package.price,
                discount: customer.discount || 0,
                status: 'UNPAID',
              }
            });
            generatedCount++;
            console.log(`[Auto-Billing] Generated unpaid invoice for ${customer.name} (${monthStr}) due at ${dueDateTime.toISOString()}`);
          }
        }

        // Move to the next month
        iterDate.setMonth(iterDate.getMonth() + 1);
      }
    }

    return generatedCount;
  } catch (error) {
    console.error('[Auto-Billing] Error in auto-generating invoices:', error);
    return 0;
  }
}
