import prisma from './db';

/**
 * Automatically checks and generates invoices for all ACTIVE or GRACE_PERIOD customers
 * whose due date and due time for the current or past months have passed, but do not
 * have an invoice generated yet.
 */
export async function autoGenerateDueInvoices() {
  try {
    const customers = await prisma.customer.findMany({
      where: {
        status: { in: ['ACTIVE', 'GRACE_PERIOD'] }
      },
      include: {
        package: true
      }
    });

    const currentDate = new Date();
    let generatedCount = 0;

    for (const customer of customers) {
      if (!customer.package) continue;

      const joinDateObj = new Date(customer.joinDate);
      
      // Start iterating from the month customer joined
      let iterDate = new Date(joinDateObj.getFullYear(), joinDateObj.getMonth(), 1);
      
      // Stop checking at the current month
      const endDate = new Date(currentDate.getFullYear(), currentDate.getMonth(), 1);

      while (iterDate <= endDate) {
        const year = iterDate.getFullYear();
        const monthNum = iterDate.getMonth();
        const monthStr = `${year}-${String(monthNum + 1).padStart(2, '0')}`; // "YYYY-MM"

        // Determine actual due date and time for this specific month
        const [dueHour, dueMinute] = (customer.dueTime || '10:00').split(':').map(Number);
        
        // Handle month end clamping (e.g. if due date is 31 but month only has 30 days)
        const lastDayOfMonth = new Date(year, monthNum + 1, 0).getDate();
        const clampedDueDate = Math.min(customer.dueDate, lastDayOfMonth);
        
        const dueDateTime = new Date(year, monthNum, clampedDueDate, dueHour ?? 10, dueMinute ?? 0, 0, 0);

        // If the current date & time has passed the due date & time
        if (currentDate >= dueDateTime) {
          // Check if invoice already exists for this customer and month
          const existing = await prisma.invoice.findUnique({
            where: {
              customerId_month: {
                customerId: customer.id,
                month: monthStr
              }
            }
          });

          if (!existing) {
            await prisma.invoice.create({
              data: {
                customerId: customer.id,
                month: monthStr,
                amount: customer.package.price,
                discount: customer.discount || 0,
                status: 'UNPAID',
              }
            });
            generatedCount++;
            console.log(`[Auto-Billing] Generated unpaid invoice for ${customer.name} (${monthStr}) due at ${dueDateTime.toISOString()}`);
          }
        }

        // Move to the next month
        iterDate.setMonth(iterDate.getMonth() + 1);
      }
    }

    // Automatically trigger daily Telegram report if there are overdue invoices
    // Runs in the background without blocking the main response
    sendTelegramOverdueReport(false).catch(err => {
      console.error('[Auto-Billing] Failed to trigger auto Telegram report:', err);
    });

    return generatedCount;
  } catch (error) {
    console.error('[Auto-Billing] Error in auto-generating invoices:', error);
    return 0;
  }
}

/**
 * Sends a list of overdue customers (past their due date and status UNPAID)
 * to the Admin's configured Telegram Chat ID.
 * @param {boolean} force - If true, bypasses the daily check and sends immediately.
 */
export async function sendTelegramOverdueReport(force = false) {
  try {
    const settings = await prisma.systemSettings.findUnique({
      where: { id: 'default' }
    });

    if (!settings || !settings.telegramBotToken || !settings.telegramChatId) {
      console.log('[Telegram-Billing] Telegram settings not configured. Skipping.');
      return false;
    }

    const currentDate = new Date();
    const todayStr = currentDate.toISOString().substring(0, 10); // "YYYY-MM-DD"

    if (!force && settings.lastSentDate === todayStr) {
      console.log(`[Telegram-Billing] Report already sent today (${todayStr}). Skipping.`);
      return false;
    }

    // Get all unpaid invoices
    const unpaidInvoices = await prisma.invoice.findMany({
      where: {
        status: 'UNPAID',
      },
      include: {
        customer: {
          include: {
            package: true
          }
        }
      }
    });

    const overdueList = [];
    let totalTunggakan = 0;

    for (const inv of unpaidInvoices) {
      if (!inv.customer) continue;

      const [year, monthVal] = inv.month.split('-').map(Number);
      const [dueHour, dueMinute] = (inv.customer.dueTime || '10:00').split(':').map(Number);
      const lastDayOfMonth = new Date(year, monthVal, 0).getDate();
      const clampedDueDate = Math.min(inv.customer.dueDate, lastDayOfMonth);
      const dueDateTime = new Date(year, monthVal - 1, clampedDueDate, dueHour, dueMinute, 0, 0);

      if (currentDate >= dueDateTime) {
        overdueList.push(inv);
        totalTunggakan += (inv.amount - (inv.discount || 0));
      }
    }

    if (overdueList.length === 0) {
      console.log('[Telegram-Billing] No overdue customers found.');
      return false;
    }

    // Format message
    const formatRupiah = (val) => {
      return new Intl.NumberFormat('id-ID', {
        style: 'currency',
        currency: 'IDR',
        maximumFractionDigits: 0
      }).format(val);
    };

    const getReadableMonth = (monthStr) => {
      const [year, month] = monthStr.split('-');
      const monthNames = [
        "Januari", "Februari", "Maret", "April", "Mei", "Juni",
        "Juli", "Agustus", "September", "Oktober", "November", "Desember"
      ];
      return `${monthNames[parseInt(month) - 1]} ${year}`;
    };

    let message = `⚠️ *LAPORAN TUNGGAKAN PELANGGAN* ⚠️\n`;
    message += `*DaraNet ISP - Tanggal: ${currentDate.toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' })}*\n\n`;
    message += `Berikut adalah daftar pelanggan yang telah melewati jatuh tempo pembayaran:\n\n`;

    overdueList.forEach((inv, index) => {
      const invNominal = inv.amount - (inv.discount || 0);
      message += `${index + 1}. *${inv.customer.name}*\n`;
      message += `   • Paket: ${inv.customer.package?.name || 'Custom'} (${formatRupiah(inv.amount)})\n`;
      if (inv.discount > 0) {
        message += `   • Potongan: -${formatRupiah(inv.discount)}\n`;
      }
      message += `   • Total Tagihan: *${formatRupiah(invNominal)}*\n`;
      message += `   • Periode: ${getReadableMonth(inv.month)}\n`;
      message += `   • Kontak WA: https://wa.me/${inv.customer.phone.replace(/[^0-9]/g, '')}\n\n`;
    });

    message += `*Total Tunggakan:* *${formatRupiah(totalTunggakan)}* dari *${overdueList.length}* pelanggan.\n\n`;
    message += `_Silakan kelola tagihan di Dashboard Utama DaraNet._`;

    // Send to Telegram API
    const telegramUrl = `https://api.telegram.org/bot${settings.telegramBotToken}/sendMessage`;
    const response = await fetch(telegramUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        chat_id: settings.telegramChatId,
        text: message,
        parse_mode: 'Markdown'
      })
    });

    if (!response.ok) {
      const errText = await response.text();
      throw new Error(`Telegram API returned error: ${errText}`);
    }

    // Update lastSentDate
    await prisma.systemSettings.update({
      where: { id: 'default' },
      data: { lastSentDate: todayStr }
    });

    console.log(`[Telegram-Billing] Overdue report successfully sent to Telegram chat ${settings.telegramChatId}`);
    return true;
  } catch (error) {
    console.error('[Telegram-Billing] Failed to send Telegram overdue report:', error);
    return false;
  }
}
