export const dynamic = 'force-dynamic';

import { NextResponse } from 'next/server';
import prisma from '@/lib/db';
import { autoGenerateDueInvoices, sendTelegramOverdueReport, sendWhatsAppOverdueReport } from '@/lib/billing-utils';

export async function GET(request) {
  try {
    const { searchParams } = new URL(request.url);
    const token = searchParams.get('token');

    // Fetch cron settings
    const settings = await prisma.systemSettings.findUnique({
      where: { id: 'default' }
    });

    const expectedToken = settings?.cronToken || '';

    // If cron token is configured, check it
    if (expectedToken && token !== expectedToken) {
      return NextResponse.json({ error: 'Token tidak valid' }, { status: 401 });
    }

    console.log('[Cron] Running daily billing and status sync...');
    
    // 1. Generate due invoices and sync customer statuses (and router statuses)
    const generatedInvoices = await autoGenerateDueInvoices();

    // 2. Trigger notifications if any overdue invoices exist (forcing reports since it is scheduled)
    const telegramSuccess = await sendTelegramOverdueReport(true);
    const whatsappSuccess = await sendWhatsAppOverdueReport(true);

    // 3. Log the cron execution
    await prisma.systemLog.create({
      data: {
        action: 'CRON_SYNC',
        message: `Sinkronisasi cron harian sukses. Tagihan baru dibuat: ${generatedInvoices}. Laporan Telegram: ${telegramSuccess ? 'Terkirim' : 'Dilewati/Gagal'}. Laporan WhatsApp: ${whatsappSuccess ? 'Terkirim' : 'Dilewati/Gagal'}.`
      }
    });

    return NextResponse.json({
      success: true,
      generatedInvoices,
      telegramSuccess,
      whatsappSuccess
    });
  } catch (error) {
    console.error('[Cron-Error] Execution failed:', error);
    
    try {
      await prisma.systemLog.create({
        data: {
          action: 'CRON_ERROR',
          message: `Eksekusi cron harian gagal: ${error.message}`
        }
      });
    } catch (e) {}

    return NextResponse.json({ error: error.message || 'Terjadi kesalahan sistem' }, { status: 500 });
  }
}
