import { NextResponse } from 'next/server';
import prisma from '@/lib/db';
import { autoGenerateDueInvoices } from '@/lib/billing-utils';

export async function GET(request) {
  try {
    // Trigger automatic billing generation for any due customers
    await autoGenerateDueInvoices();

    const { searchParams } = new URL(request.url);
    const search = searchParams.get('search') || '';
    const status = searchParams.get('status') || '';
    const packageId = searchParams.get('packageId') || '';

    // Build filter query
    let whereClause = {};

    if (search) {
      whereClause.OR = [
        { name: { contains: search, mode: 'insensitive' } },
        { phone: { contains: search, mode: 'insensitive' } },
        { address: { contains: search, mode: 'insensitive' } },
        { ipAddress: { contains: search, mode: 'insensitive' } },
        { pppoeUsername: { contains: search, mode: 'insensitive' } },
      ];
    }

    if (status) {
      whereClause.status = status;
    }

    if (packageId) {
      whereClause.packageId = packageId;
    }

    const customers = await prisma.customer.findMany({
      where: whereClause,
      include: {
        package: true,
      },
      orderBy: { name: 'asc' },
    });

    return NextResponse.json(customers);
  } catch (error) {
    console.error('Failed to fetch customers:', error);
    return NextResponse.json({ error: 'Gagal mengambil data pelanggan' }, { status: 500 });
  }
}

export async function POST(request) {
  try {
    const data = await request.json();
    const { name, phone, address, ipAddress, pppoeUsername, pppoePassword, dueDate, dueTime, discount, status, packageId, joinDate } = data;

    if (!name || !phone || !address || !dueDate || !status || !packageId) {
      return NextResponse.json({ error: 'Field utama wajib diisi' }, { status: 400 });
    }

    const customer = await prisma.customer.create({
      data: {
        name,
        phone,
        address,
        ipAddress,
        pppoeUsername,
        pppoePassword,
        dueDate: parseInt(dueDate),
        dueTime: dueTime || '10:00',
        discount: parseFloat(discount) || 0,
        status,
        packageId,
        joinDate: joinDate ? new Date(joinDate) : new Date(),
      },
      include: {
        package: true,
      },
    });

    return NextResponse.json(customer, { status: 201 });
  } catch (error) {
    console.error('Failed to create customer:', error);
    return NextResponse.json({ error: 'Gagal membuat data pelanggan' }, { status: 500 });
  }
}
