import { NextResponse } from 'next/server';
import prisma from '@/lib/db';
import { autoGenerateDueInvoices } from '@/lib/billing-utils';

export async function GET(request) {
  try {
    // Trigger automatic billing generation for any due customers
    await autoGenerateDueInvoices();

    const { searchParams } = new URL(request.url);
    const month = searchParams.get('month') || '';
    const status = searchParams.get('status') || '';
    const search = searchParams.get('search') || '';

    let whereClause = {};

    if (month) {
      whereClause.month = month;
    }

    if (status) {
      whereClause.status = status;
    }

    if (search) {
      whereClause.customer = {
        name: { contains: search, mode: 'insensitive' }
      };
    }

    const invoices = await prisma.invoice.findMany({
      where: whereClause,
      include: {
        customer: {
          include: {
            package: true
          }
        }
      },
      orderBy: [
        { month: 'desc' },
        { customer: { name: 'asc' } }
      ]
    });

    return NextResponse.json(invoices);
  } catch (error) {
    console.error('Failed to fetch invoices:', error);
    return NextResponse.json({ error: 'Gagal mengambil data tagihan' }, { status: 500 });
  }
}
