import { NextResponse } from 'next/server';
import prisma from '@/lib/db';
import { autoGenerateDueInvoices } from '@/lib/billing-utils';

export async function GET(request, { params }) {
  try {
    // Sync due invoices first
    await autoGenerateDueInvoices();

    const { id } = params;
    const customer = await prisma.customer.findUnique({
      where: { id },
      include: {
        package: true,
        invoices: {
          orderBy: { month: 'desc' },
          take: 12, // Show last 12 invoices
        },
      },
    });

    if (!customer) {
      return NextResponse.json({ error: 'Pelanggan tidak ditemukan' }, { status: 404 });
    }

    return NextResponse.json(customer);
  } catch (error) {
    console.error('Failed to get customer details:', error);
    return NextResponse.json({ error: 'Gagal mengambil detail pelanggan' }, { status: 500 });
  }
}

export async function PUT(request, { params }) {
  try {
    const { id } = params;
    const data = await request.json();
    const { name, phone, address, ipAddress, pppoeUsername, pppoePassword, dueDate, dueTime, discount, status, packageId, joinDate } = data;

    const updated = await prisma.customer.update({
      where: { id },
      data: {
        name,
        phone,
        address,
        ipAddress,
        pppoeUsername,
        pppoePassword,
        dueDate: parseInt(dueDate),
        dueTime: dueTime || '10:00',
        discount: discount !== undefined ? parseFloat(discount) : undefined,
        status,
        packageId,
        joinDate: joinDate ? new Date(joinDate) : undefined,
      },
      include: {
        package: true,
      },
    });

    return NextResponse.json(updated);
  } catch (error) {
    console.error('Failed to update customer:', error);
    return NextResponse.json({ error: 'Gagal memperbarui data pelanggan' }, { status: 500 });
  }
}

export async function DELETE(request, { params }) {
  try {
    const { id } = params;

    // Direct cascade delete is handled by postgres since we configured onDelete: Cascade on Invoice relation
    await prisma.customer.delete({
      where: { id },
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Failed to delete customer:', error);
    return NextResponse.json({ error: 'Gagal menghapus data pelanggan' }, { status: 500 });
  }
}
